// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Container: typeof import('./../src/layouts/container.vue')['default']
    Header: typeof import('./../src/layouts/header.vue')['default']
    Layout: typeof import('./../src/layouts/layout.vue')['default']
    MenuItem: typeof import('./../src/layouts/menu-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./../src/layouts/side-menu.vue')['default']
    Test: typeof import('./../src/components/test.vue')['default']
    ToggleDark: typeof import('./../src/layouts/toggleDark.vue')['default']
  }
}
